# Generated by Django 3.2.7 on 2022-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_auto_20220505_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Telecom', 'Telecom')], default='Civil', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp908', max_length=70),
        ),
    ]
